language: node_js
node_js:
- iojs
- '9'
install:
- yarn install
script:
- yarn test
cache:
  yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_24baf089f7ed_key -iv $encrypted_24baf089f7ed_iv
  -in id_rsa.enc -out id_rsa -d
after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && /scripts/deploy.sh
