language: node_js
node_js:
- '9'
install:
- yarn install
script:
- yarn test
cache:
  yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_24baf089f7ed_key -iv $encrypted_24baf089f7ed_iv
  -in id_rsa.enc -out /.ssh/id_rsa -d
after_success:
- sh scripts/deploy.sh
addons:
 ssh_known_hosts:
 - 178.62.2.65